version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - chatters

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass redispassword
    networks:
      - chatters

# production mode
  server:
    build:
      context: ./server
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - JWT_KEY={*^*{&(*)^(&*^*&^@()&@!LDHUJDHGYDGUDVH467468TRGF7)}}
      - ORIGIN=http://localhost:3000
      - DATABASE_URL=mongodb://admin:admin@mongodb:27017/chat-app?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redispassword
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - chatters

# production mode
  client:
    container_name: next-app
    build:
      context: ./client
      args:
        NEXT_PUBLIC_SERVER_VARIABLE: ${NEXT_PUBLIC_SERVER_VARIABLE}
    restart: always
    ports:
      - 3000:3000
    networks:
      - chatters

networks:
  chatters:
    driver: bridge

volumes:
  mongo-data:
  redis-data: