const HOST = process.env.NEXT_PUBLIC_SERVER_URL;

const AUTH_ROUTES = "api/auth";
const SIGN_UP_ROUTE = `${AUTH_ROUTES}/sign-up`;
const LOGIN_ROUTE = `${AUTH_ROUTES}/login`;
const GET_USER_INFO_ROUTE = `${AUTH_ROUTES}/user-info`;
const UPDATE_PROFILE_ROUTE = `${AUTH_ROUTES}/user-info`;
const ADD_PROFILE_PIC_ROUTE = `${AUTH_ROUTES}/profile-image`;
const DELETE_PROFILE_PIC_ROUTE = `${AUTH_ROUTES}/profile-image`;
const LOGOUT_ROUTE = `${AUTH_ROUTES}/logout`;

const CONTACT_ROUTES = "api/contact";
const SEARCH_CONTACT_ROUTE = `${CONTACT_ROUTES}/search-contact`;
const GET_PERSONAL_CONTACTS_ROUTE = `${CONTACT_ROUTES}/personal-contacts`;

const MESSAGE_ROUTES = "api/message";
const GET_MESSAGES_ROUTE = `${MESSAGE_ROUTES}/messages`;
const UPLOAD_FILE_ROUTE = `${MESSAGE_ROUTES}/file`;

const GROUP_ROUTES = "api/group";
const ADD_GROUP_PIC_ROUTE = `${GROUP_ROUTES}/group-pic`;
const REMOVE_GROUP_PIC_ROUTE = `${GROUP_ROUTES}/remove-group-pic`;
const CREATE_GROUP_ROUTE = `${GROUP_ROUTES}/create-group`;
const GET_USER_GROUPS_ROUTE = `${GROUP_ROUTES}/user-groups`;
const GET_GROUP_MESSAGES_ROUTE = `${GROUP_ROUTES}/group-messages`;

export {
  HOST,
  AUTH_ROUTES,
  SIGN_UP_ROUTE,
  LOGIN_ROUTE,
  LOGOUT_ROUTE,
  GET_USER_INFO_ROUTE,
  UPDATE_PROFILE_ROUTE,
  ADD_PROFILE_PIC_ROUTE,
  DELETE_PROFILE_PIC_ROUTE,
  CONTACT_ROUTES,
  GET_PERSONAL_CONTACTS_ROUTE,
  SEARCH_CONTACT_ROUTE,
  GET_MESSAGES_ROUTE,
  UPLOAD_FILE_ROUTE,
  ADD_GROUP_PIC_ROUTE,
  REMOVE_GROUP_PIC_ROUTE,
  CREATE_GROUP_ROUTE,
  GET_USER_GROUPS_ROUTE,
  GET_GROUP_MESSAGES_ROUTE,
};
